apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: discord-bot-ask-100x
  annotations:
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '1'
        run.googleapis.com/cpu-throttling: 'false'
    spec:
      containerConcurrency: 1
      timeoutSeconds: 3600
      containers:
      - image: gcr.io/PROJECT_ID/discord-bot-ask-100x:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: DISCORD_TOKEN
          value: "YOUR_DISCORD_TOKEN"
        - name: DAILY_MESSAGE_LIMIT
          value: "10"
        - name: LOG_LEVEL
          value: "INFO"
        resources:
          limits:
            cpu: '1'
            memory: 512Mi
